.PHONY: clean All

All:
	@echo "----------Building project:[ chapter2 - Debug ]----------"
	@"$(MAKE)" -f  "chapter2.mk"
clean:
	@echo "----------Cleaning project:[ chapter2 - Debug ]----------"
	@"$(MAKE)" -f  "chapter2.mk" clean
