.PHONY: clean All

All:
	@echo "----------Building project:[ Assignment_02 - Debug ]----------"
	@"$(MAKE)" -f  "Assignment_02.mk"
clean:
	@echo "----------Cleaning project:[ Assignment_02 - Debug ]----------"
	@"$(MAKE)" -f  "Assignment_02.mk" clean
